# Test your FastAPI endpoints
###
GET http://127.0.0.1:8000/todos
Accept: application/json

###
GET http://127.0.0.1:8000/todos/9
Accept: application/json

###
POST http://127.0.0.1:8000/todos/
Accept: application/json
Content-Type: application/json

{
  "title": "new todo4",
  "description": "new_todo4",
  "priority": 4,
  "completed": false
}

###
PUT http://127.0.0.1:8000/todos/99
Accept: application/json
Content-Type: application/json

{
  "title": "new todo3",
  "description": "new_todo3",
  "priority": 1,
  "completed": false
}

###
PATCH http://127.0.0.1:8000/todos/6
Accept: application/json
Content-Type: application/json

{
  "completed": true
}