###
GET http://localhost:8000/users/
Accept: application/json

###
POST http://localhost:8000/users/
Accept: application/json
Content-Type: application/json

{
  "username": "basharalhusein",
  "email": "bashar.alhusein@hotmail.com",
  "password": "12345678",
  "first_name": "Bashar",
  "last_name": "Alhusein"
}